### ISSUE TITLE
fail to build on ubuntu 18.04

### ISSUE THREAD

**Issue by prudhomm** [whoshuu/cpr#496]
cpr fails to build on 18.04 due to a missing define in curl version 

it is strange that it is not detected by github actions on ubuntu 18.04
I installed `libcurl4-openssl-dev` and it seems that github virtual-environments
could it be that curl is fetched in all the actions, and so, such an issue is not detected ?
In my case I have to use the system curl

here is the error
```
/build/feelpp-0.109.0~alpha.1/feelpp/contrib/cpr/cpr/session.cpp:168:55: error: use of undeclared identifier 'CURLAUTH_BEARER'; did you mean 'CURLOPT_HEADER'?
--
  | curl_easy_setopt(curl_->handle, CURLOPT_HTTPAUTH, CURLAUTH_BEARER);
  | ^~~~~~~~~~~~~~~
  | CURLOPT_HEADER
  | /usr/include/x86_64-linux-gnu/curl/curl.h:2744:72: note: expanded from macro 'curl_easy_setopt'
  | #define curl_easy_setopt(handle,opt,param) curl_easy_setopt(handle,opt,param)
  | ^
  | /usr/include/x86_64-linux-gnu/curl/curl.h:1059:3: note: 'CURLOPT_HEADER' declared here
  | CINIT(HEADER, LONG, 42),       /* throw the header out too */
  | ^
  | /usr/include/x86_64-linux-gnu/curl/curl.h:896:24: note: expanded from macro 'CINIT'
  | #define CINIT(na,t,nu) CURLOPT_ ## na = CURLOPTTYPE_ ## t + nu
  | ^
  | <scratch space>:349:1: note: expanded from here
  | CURLOPT_HEADER
  | ^
```

**Comment by prudhomm** [comment]
on ubuntu 20.04 curl is at 7.68.0-1ubuntu2.4 while on 18.04 it is at 7.58.0-2ubuntu3.12

**Comment by prudhomm** [comment]
here is the failing build on github action: https://github.com/feelpp/cpr/runs/1656942263?check_suite_focus=true

**Comment by prudhomm** [comment]
it is possible to define the missing define
see here https://github.com/feelpp/cpr/pull/1

in that case the build is fine but two tests are failing:
https://github.com/feelpp/cpr/runs/1656991453?check_suite_focus=true#step:4:1369

**Comment by COM8** [comment]
Thanks for reporting this bug!
The problem is, `CURLAUTH_BEARER` got added with `libcurl` 7.61.0.
Before that you had to add the `Authorization` header manually.

I disabled `Bearer` in case the `libcurl` version is < 7.61.0.
The documentation has been updated correspondingly.
https://whoshuu.github.io/cpr/introduction.html#authentication (bottom)
