### PR TITLE
Fix build with curl 7.62.0

### PR DESCRIPTION
**Pull request by sunpoet**
from CHANGES:
ssl: deprecate CURLE_SSL_CACERT in favour of a unified error code
Long live CURLE_PEER_FAILED_VERIFICATION

### CODE REVIEW

**Comment by RPGillespie6** [comment]
Need this PR to resolve GCC error:

```
/build_env/gcc9_build/ext/cpr/libcpr-prefix/src/libcpr/cpr/error.cpp:41:9: error: duplicate case value
   41 |         case CURLE_SSL_CACERT:
      |         ^~~~
/build_env/gcc9_build/ext/cpr/libcpr-prefix/src/libcpr/cpr/error.cpp:25:9: note: previously used here
   25 |         case CURLE_PEER_FAILED_VERIFICATION:
      |         ^~~~

```

**Comment by TheAssassin** [comment]
I've implemented a similar workaround:

```diff
diff --git a/cpr/error.cpp b/cpr/error.cpp
index 713cb10..e37f8d9 100644
--- a/cpr/error.cpp
+++ b/cpr/error.cpp
@@ -38,8 +38,10 @@ ErrorCode Error::getErrorCodeForCurlError(std::int32_t curl_code) {
             return ErrorCode::SSL_LOCAL_CERTIFICATE_ERROR;
         case CURLE_SSL_CIPHER:
             return ErrorCode::GENERIC_SSL_ERROR;
+#if CURLE_PEER_FAILED_VERIFICATION != CURLE_SSL_CACERT
         case CURLE_SSL_CACERT:
             return ErrorCode::SSL_CACERT_ERROR;
+#endif
         case CURLE_USE_SSL_FAILED:
             return ErrorCode::GENERIC_SSL_ERROR;
         case CURLE_SSL_ENGINE_INITFAILED:
```

Of course, this proposal is more elegant. I wish I had seen it earlier.

This project seems really dead. I wish someone would fork and take over maintenance.

**Comment by SleepingSoul** [comment]
Yeah. the same issue. Please, merge it :)

**Comment by Quent42340** [comment]
@whoshuu any reason why this is not merged yet?

**Comment by TheAssassin** [comment]
There hasn't been any activity within the last 1.5 years. Maybe it's time to fork this project as a community project. If @whoshuu should ever return/respond, the projects could be merged again.

**Comment by whoshuu** [comment]
This is great. Thanks @sunpoet!

@TheAssassin as it happens, my career has taken me off the road of C++ enlightenment. In the next couple of months that may change for the better, and in the meantime I'll try to give the project some of my attention.

The project has more legs than I initially thought was possible. In light of that, and to protect against the single bus factor that is me, I think the healthiest thing to do is to have 2-3 maintainers on the project that can help guide it in the right direction.

Though making a call on who to have as a maintainer is hard (and something I've never done before), it is better than the current state of affairs.

**Comment by sunpoet** [comment]
Thank you, @whoshuu.

**Comment by TheAssassin** [comment]
@whoshuu good to see you're open to the idea of sharing responsibility. Let me know if you need help finding a strategy that works for you and for the project. I'm pretty sure there's people interested in this.
